-- Inserir bairros
INSERT INTO bairros (id, nome, regiao) VALUES
  (1315, 'Barra Olímpica', 'Barra Da Tijuca E Jacarepaguá'),
  (1265, 'Freguesia (jacarepaguá)', 'Barra Da Tijuca E Jacarepaguá'),
  (1150, 'Abolição', 'Zona Norte'),
  (1153, 'Anil', 'Barra Da Tijuca E Jacarepaguá'),
  (1154, 'Bangu', 'Zona Oeste'),
  (1155, 'Barra Da Tijuca', 'Barra Da Tijuca E Jacarepaguá'),
  (1156, 'Barra De Guaratiba', 'Zona Oeste'),
  (1157, 'Bento Ribeiro', 'Zona Norte'),
  (1158, 'Botafogo', 'Zona Sul'),
  (1161, 'Cacuia', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1162, 'Campo Grande', 'Zona Oeste'),
  (1164, 'Catete', 'Zona Sul'),
  (1165, 'Centro', 'Centro'),
  (1168, 'Copacabana', 'Zona Sul'),
  (1171, 'Curicica', 'Barra Da Tijuca E Jacarepaguá'),
  (1174, 'Engenho Da Rainha', 'Zona Norte'),
  (1175, 'Engenho De Dentro', 'Zona Norte'),
  (1176, 'Engenho Novo', 'Zona Norte'),
  (1177, 'Estácio', 'Centro'),
  (1178, 'Flamengo', 'Zona Sul'),
  (1179, 'Freguesia', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1181, 'Gamboa', 'Centro'),
  (1182, 'Gávea', 'Zona Sul'),
  (1183, 'Glória', 'Centro'),
  (1184, 'Grajaú', 'Grande Tijuca'),
  (1185, 'Guaratiba', 'Zona Oeste'),
  (1186, 'Higienópolis', 'Zona Norte'),
  (1187, 'Honório Gurgel', 'Zona Norte'),
  (1188, 'Humaitá', 'Zona Sul'),
  (1190, 'Ipanema', 'Zona Sul'),
  (1191, 'Irajá', 'Zona Norte'),
  (1193, 'Jardim América', 'Zona Norte'),
  (1194, 'Jardim Botânico', 'Zona Sul'),
  (1195, 'Jardim Carioca', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1196, 'Jardim Guanabara', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1197, 'Lagoa', 'Zona Sul'),
  (1198, 'Lapa', 'Centro'),
  (1199, 'Laranjeiras', 'Zona Sul'),
  (1200, 'Leblon', 'Zona Sul'),
  (1201, 'Leme', 'Zona Sul'),
  (1203, 'Madureira', 'Zona Norte'),
  (1206, 'Manguinhos', 'Zona Norte'),
  (1207, 'Maracanã', 'Grande Tijuca'),
  (1209, 'Méier', 'Zona Norte'),
  (1210, 'Olaria', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1212, 'Padre Miguel', 'Zona Oeste'),
  (1214, 'Pechincha', 'Barra Da Tijuca E Jacarepaguá'),
  (1215, 'Pedra De Guaratiba', 'Zona Oeste'),
  (1218, 'Piedade', 'Zona Norte'),
  (1219, 'Pilares', 'Zona Norte'),
  (1220, 'Pitangueiras', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1222, 'Praça Da Bandeira', 'Grande Tijuca'),
  (1223, 'Praça Seca', 'Barra Da Tijuca E Jacarepaguá'),
  (1224, 'Ramos', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1225, 'Realengo', 'Zona Oeste'),
  (1226, 'Ilha De Paquetá', 'Centro'),
  (1227, 'Paciência', 'Zona Oeste'),
  (1228, 'Recreio Dos Bandeirantes', 'Barra Da Tijuca E Jacarepaguá'),
  (1229, 'Riachuelo', 'Zona Norte'),
  (1230, 'Ribeira', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1232, 'Rio Comprido', 'Centro'),
  (1236, 'Santa Cruz', 'Zona Oeste'),
  (1237, 'Santa Teresa', 'Centro'),
  (1239, 'Santo Cristo', 'Centro'),
  (1240, 'São Conrado', 'Zona Sul'),
  (1241, 'Saúde', 'Centro'),
  (1243, 'Sepetiba', 'Zona Oeste'),
  (1245, 'Taquara', 'Barra Da Tijuca E Jacarepaguá'),
  (1246, 'Tauá', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1247, 'Tijuca', 'Grande Tijuca'),
  (1248, 'Urca', 'Zona Sul'),
  (1250, 'Vila Da Penha', 'Zona Norte'),
  (1251, 'Vila Isabel', 'Grande Tijuca'),
  (1253, 'Vila Kosmos', 'Zona Norte'),
  (1254, 'Vila Valqueire', 'Barra Da Tijuca E Jacarepaguá'),
  (1256, 'Zumbi', 'Ilha Do Governador E Zona Da Leopoldina'),
  (1270, 'Vargem Grande', 'Barra Da Tijuca E Jacarepaguá'),
  (1274, 'Jardim Sulacap', 'Zona Oeste'),
  (1278, 'Alto Da Boa Vista', 'Grande Tijuca'),
  (1280, 'Encantado', 'Zona Norte'),
  (1286, 'Todos Os Santos', 'Zona Norte'),
  (1306, 'Turiaçu', 'Zona Norte'),
  (1313, 'São Cristóvão', 'Centro'),
  (1314, 'Quintino Bocaiúva', 'Zona Norte')
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome,
  regiao = EXCLUDED.regiao,
  updated_at = NOW();

